### ISSUE TITLE
Error when issuing command during interactive hijack

### ISSUE THREAD

**Issue by honigbij** [micheloosterhof/kippo#25] opened 2015-03-12 15:35 UTC
When you hijack a session and issue a command, the following error is in the log:

 ```File "kippo/kippo/core/interact.py", line 69, in applicationDataReceived
            self.interacting.ttylog_file,
        exceptions.AttributeError: 'HoneyPotInteractiveProtocol' object has no attribute 'ttylog_file' ```

This can be solved by adding a line to protcol.py:
```       self.ttylog_file = transport.ttylog_file```

in method connectionMade of class HoneyPotInteractiveProtocol.

I will send a pull request with the fix.

**Comment by micheloosterhof** [comment] 2015-03-15 07:12
Duplicate of #26

**Closed by micheloosterhof** 2015-03-15 07:12 UTC
Labels: duplicate
